language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: "3.4"

    - os: linux
      dist: trusty
      python: "3.5"

    - os: linux
      dist: trusty
      python: "3.6-dev"

    - os: osx
      language: generic
      python: "3.4"
      env:
        - PYTHON_VERSION=3.4.4

    - os: osx
      language: generic
      python: "3.5"
      env:
        - PYTHON_VERSION=3.5.2

  allow_failures:
    - os: osx

#python:
#  - "3.4"
#  - "3.5"
#  - "3.6"
#
#os:
#  - linux
#  - osx

# command to install dependencies
install:
  - pip install requests progressbar2 prettytable pytest pytest-catchlog coverage codecov pytest-cov
  - tests/travis.sh
  - pip install -e .

env:
 - PYTHON_TEST=1

# command to run tests
script:
  - py.test --cov=./
# - py.test tests/test_nicodown.py -v
# - py.test tests/test_nicoml.py -v


after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
#  - coverage run --branch --omit="nicotools/stubs/*" tests/test_nicodown.py
#  - coverage run --branch --omit="nicotools/stubs/*" tests/test_nicoml.py
#  - coverage html -d "tests/coverage/"

notifications:
  email:
    recipients:
      - window100@gmail.com
    on_success: always

branches:
  only:
  - master
  - develop
