language: python

python:
 - "3.6-dev"
 - "3.5"
 - "3.4"

env:
 - TEST_ASYNC=0
 - TEST_ASYNC=1

install:
  - pip install pytest pytest-catchlog codecov pytest-cov
  - pip install -e .

env:
 - PYTHON_TEST=1

script:
  - py.test --cov=./


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x tests/travis.sh
  - tests/travis.sh

after_failure:
  - chmod +x tests/travis.sh
  - tests/travis.sh

notifications:
  email:
    recipients:
      - window100@gmail.com
    on_success: always

branches:
  only:
  - master
  - develop
